/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import project from "public/project.png";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Renita Gidlund</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="w-8/9 bg-highlight m-3 flex flex-col justify-between rounded-xl pt-12">
          <div className="text-center">
            {/* eslint-disable-next-line react/no-unescaped-entities */}
            <h1 className="bg-gradient-to-r from-orange-600 via-rose-500 to-amber-500 bg-clip-text text-center text-4xl font-bold text-transparent font-header">
              Hi! I'm Renita!
            </h1>
            <h2 className="text-2xl">Welcome to my portfolio.</h2>
            <div className="pt-10 leading-relaxed">
              I am a full-stack software developer who likes solving problems for fun, building cool things with code, and above all, 
              <span className="font-pretty text-2xl leading-3">
              &nbsp;making it pretty.
              </span>

            </div>
          </div>
          <div className="bg-gradient-to-br from-orange-600 via-rose-500 to-amber-400 rounded-xl w-52 h-52 m-10 shadow-lg shadow-gray-700 dark:shadow-black">
          <div className="bg-white w-48 h-48 m-1 rounded-xl p-2 flex flex-col text-center text-black">
            <Link href="/projects">
              
            My favorite project:
            <motion.div>
              <Image src={project} alt="preview of project" className="hover:hue-rotate-180"/>
            </motion.div>
            </Link>
          </div>
          </div>
        </div>
      </main>
    </>
  );
}
