/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import project from 'public/project.png'
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Renita Gidlund</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="m-10 flex w-4/5 flex-row justify-between rounded-xl bg-highlight p-20">
          <div className="text-center font-serif">
            {/* eslint-disable-next-line react/no-unescaped-entities */}
            <h1 className="text-5xl">Hi! I'm Renita!</h1>
            <h2 className="text-2xl">Welcome to my portfolio.</h2>
            <div className="pt-10">This is my 30 second elevator pitch, where I'm going to tell you a few enticing things about myself! It might be more like 10 seconds if we're being honest.</div>
          </div>
          <div className="relative w-500 m-10 font-serif">
          <Link href="/projects">
            My favorite project:
          <Image
            src={project}
            alt="preview of project"
          />
          </Link>
          </div>
        </div>
      </main>
    </>
  );
}
