/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import project from "public/project.png";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Renita Gidlund</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <div className="w-8/9 bg-highlight m-10 flex flex-col justify-between rounded-xl p-20">
          <div className="text-center font-serif">
            {/* eslint-disable-next-line react/no-unescaped-entities */}
            <h1 className="bg-gradient-to-r from-red-500 via-yellow-500 to-cyan-500 bg-clip-text text-center text-4xl font-bold text-transparent">
              Hi! I'm Renita!
            </h1>
            <h2 className="text-2xl">Welcome to my portfolio.</h2>
            <div className="pt-10">
              This is my 30 second elevator pitch, where I'm going to tell you a
              few enticing things about myself! It might be more like 10 seconds
              if we're being honest.
            </div>
          </div>
          <div className="w-500 relative m-10 font-serif">
            {/* <Link href="/projects"> */}
            My favorite project:
            <motion.div>
              <Image src={project} alt="preview of project" />
            </motion.div>
            {/* </Link> */}
          </div>
        </div>
      </main>
    </>
  );
}
